# Extracting Trials With Given Properties & Plotting Results

In [1]:
import pandas as pd
import numpy as np
import h5py
import matplotlib.pyplot as plt
import dask.array as da

In [2]:
df = pd.read_csv("TrialInfo.csv")
df

,AnimalCode,Date,TrialID,Time,BFMTime,Duration,Contrast,PerceptualCat,ReactTime,Rewarded?,Enticed?,Seen?,Consume?,Attrition?,Recording,EngagementScore,EngagementScore_S20,MovieFile,Delay
0,cfm001mjr,240506,240506_1_001,3.198,1.841983,0.529,0.060,3,11.880,0,0,0,0,1,1,0.000000,0.000000,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...,-2.832001
1,cfm001mjr,240506,240506_1_002,6.353,4.996983,0.522,0.023,1,8.725,0,0,0,0,1,1,0.000000,0.000000,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...,-2.832001
2,cfm001mjr,240506,240506_1_003,10.228,8.871983,0.532,0.000,1,4.850,0,0,0,0,1,1,0.000000,0.057143,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...,-2.832001
3,cfm001mjr,240506,240506_1_004,14.599,13.242983,0.521,0.024,1,0.479,1,1,1,1,1,1,0.285714,0.086735,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...,-2.832001
4,cfm001mjr,240506,240506_1_005,43.217,41.860983,0.550,0.023,1,4.464,0,0,0,0,1,1,0.000000,0.130952,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...,-2.832001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2498,cfm001mjr,240522,240522_1_439,933.166,934.220085,0.539,0.013,1,NaN,0,0,0,0,1,1,0.000000,0.000000,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024052...,-0.421899
2499,cfm001mjr,240522,240522_1_441,937.933,938.987085,0.540,0.020,1,NaN,0,0,0,0,1,1,0.000000,0.000000,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024052...,-0.421899
2500,cfm001mjr,240522,240522_1_442,939.876,940.930085,0.507,0.045,2,NaN,0,0,0,0,1,1,0.000000,0.000000,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024052...,-0.421899
2501,cfm001mjr,240522,240522_1_445,945.859,946.913085,0.509,0.013,1,NaN,0,0,0,0,1,1,0.000000,0.000000,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024052...,-0.421899
2502,cfm001mjr,240522,240522_1_446,947.549,948.603085,0.523,0.018,1,NaN,0,0,0,0,1,1,0.000000,0.000000,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024052...,-0.421899

## Trial Extraction

In [18]:
def find_trials(df, **filters):
    """
    Finds trials from df that match the specified properties.

    Args:
    - df (pd.DataFrame): DataFrame containing trial information.
    - filters (dict): Key-value pairs of column names and values to filter by.
      - Supported keys include 'Date', 'Recording', 'PerceptualCat', 'Rewarded', etc.
      - If a parameter is not specified, it is ignored in filtering.

    Returns:
    - pd.DataFrame: Filtered dataframe containing TrialID, BFMTime, Duration, and MovieFile.
    """

    # Start with full DataFrame and apply filters dynamically
    filtered_df = df.copy()

    for key, value in filters.items():
        if key in df.columns and value is not None:
            filtered_df = filtered_df[filtered_df[key] == value]

    return filtered_df[["TrialID", "BFMTime", "Duration", "MovieFile"]]

trials_df = find_trials(df, Date=240506, PerceptualCat=1, Recording=1)
trials_df

,TrialID,BFMTime,Duration,MovieFile
1,240506_1_002,4.996983,0.522,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
2,240506_1_003,8.871983,0.532,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
3,240506_1_004,13.242983,0.521,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
4,240506_1_005,41.860983,0.550,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
5,240506_1_006,45.529983,0.527,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
7,240506_1_008,78.911983,0.524,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
9,240506_1_010,93.448983,0.529,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
11,240506_1_012,100.248983,0.513,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
12,240506_1_013,119.764983,0.560,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
13,240506_1_014,160.435983,0.541,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
14,240506_1_015,168.039983,0.527,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
15,240506_1_016,183.616983,0.569,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
16,240506_1_017,187.068983,0.556,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
17,240506_1_018,198.764983,0.543,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
18,240506_1_019,207.463983,0.563,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
19,240506_1_020,210.908983,0.525,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
21,240506_1_022,237.305983,0.524,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
23,240506_1_024,251.401983,0.534,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
24,240506_1_025,268.129983,0.506,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
25,240506_1_026,276.366983,0.538,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
27,240506_1_028,313.626983,0.567,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
28,240506_1_029,330.404983,0.547,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
30,240506_1_031,376.450983,0.529,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
31,240506_1_032,410.051983,0.515,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
32,240506_1_033,415.131983,0.522,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
34,240506_1_035,442.441983,0.529,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
36,240506_1_037,450.527983,0.517,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
38,240506_1_039,483.346983,0.527,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
39,240506_1_040,491.450983,0.530,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
40,240506_1_041,503.450983,0.511,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
42,240506_1_043,512.580983,0.528,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
43,240506_1_044,516.751983,0.525,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
45,240506_1_046,547.038983,0.516,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
46,240506_1_047,550.190983,0.501,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
48,240506_1_049,573.221983,0.556,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
50,240506_1_051,611.790983,0.537,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
51,240506_1_052,615.185983,0.522,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
52,240506_1_053,619.511983,0.554,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
54,240506_1_055,632.547983,0.563,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
55,240506_1_056,637.140983,0.593,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...
56,240506_1_057,642.663983,0.529,N:/GEVI_Wave/Analysis/Visual/cfm001mjr/2024050...